tasks:
  - name: aws-cli
    before: |
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -o awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT
      bash bin/ecr/login
      - name: cdk
  - name: npm
    before: |
      npm install - g npm@10.0.0
      cd /frontend-react-ts
      npm install
  - name: aws cdk
    before: |
      npm install aws-cdk -g
  